### ISSUE TITLE
V 2.0 stopped working

### ISSUE THREAD

**Issue by Lansuper** [ralfvd/nl.bevlogenheid.evohome#20]
The beta version of the app shows shortly the temperatures and then stops.

**Comment by ralfvd** [comment]
What do you mean with 'it stops' ?  Don't you see any more updates of the temperature? Can you elaborate on this, and maybe send a diagnostic report so I  can take a look ?

**Comment by Lansuper** [comment]
Diagnostic dump 2b681ce7-9c07-4484-bc59-ffda2407709a
I can’t enter username and password, app responds with [not_running]

**Comment by ralfvd** [comment]
I did receive the report, but it is empty, which indicates the app is indeed not running.  Did you try to start it a couple of times today? I do get crash reports for a bug I introduced.  

Do you have any thermostats already configured (from the V1 app), or did you start with a clean slate ? If there are no devices yet, the app will crash soon after start. So then you are in a loop that you cannot enter username/password.

Version 2.0.1 (which should solve this 'no-thermostat-bug')  is pending approval in the app store.

**Comment by Lansuper** [comment]
I have thermostats from v1 (3 zones) and temperature readings are showing for a couple of seconds after restart. This changes in an exclamationmark. Now trying to figure out how to get a screenprint to you...

**Comment by ralfvd** [comment]
Hmmm, strange that the log is then completely empty. I would expect to see ‘something’ like this:

-=-
---- stdout ----
2019-01-15 21:24:44 [log] [Evohome] Evohome app started
-----
5 minute update routine
quickaction read
evohomey.login
token not yet expired
get account_info
login successfull
2019-01-15 21:24:45 [log] [ManagerDrivers] [thermostat] [0] device init name: name_1
2019-01-15 21:24:45 [log] [ManagerDrivers] [thermostat] [1] device init name: name_2-=-

Are you able to use the GitHub version and run it locally? Then you’ll see this output on your own laptop/pc, that might make things easier.




On 15 January 2019 at 21:21:55, Lansuper (notifications@github.com) wrote:

I have thermostats from v1 (3 zones) and temperature readings are showing for a couple of seconds after restart. This changes in an exclamationmark. Now trying to figure out how to get a screenprint to you...

**Comment by Lansuper** [comment]
Sorry, don’t know how to install from Github. In version 2.0.2 still the same problem. Username and password added, devices present, app unexpectedly stopped...

**Comment by ralfvd** [comment]
I see the crash logs coming in, so I know where it is going wrong. I am now trying to simulate the same circumstances to see how this should be fixed and that I can verify the fix. 

On 16 January 2019 at 16:50:24, Lansuper (notifications@github.com) wrote:

Sorry, don’t know how to install from Github. In version 2.0.2 still the same problem. Username and password added, devices present, app unexpectedly stopped...

**Comment by Swiftnesses** [comment]
Not working for me either, stack trade shows:

https://imgur.com/a/wjDsyL9

**Comment by ralfvd** [comment]
Jup, that line did help for some issues, but not all. The problem is in the login routine. I am working on an updated version that should cover this.

Sorry for the inconvenience! 



On 16 January 2019 at 21:17:39, Swiftnesses (notifications@github.com) wrote:

Not working for me either, stack trade shows:

**Comment by Swiftnesses** [comment]
We'll forgive you ;-)

**Comment by Lansuper** [comment]
Is there any chance on a fix for this problem or should I downgrade to v1 for now?

**Comment by ralfvd** [comment]
The fix is already available in github, but it is still pending approval by athom. A lot of other apps are also waiting approval. 

There 3 options:

1) go back to 1 (but there will be issues in that one too)
2) install the github version via cli
3) send me your email address you use on your homey. I’ll then add you to the “alpha” channel in the App Store where you can install the latest version. This one needs no approval by athom. 

Or wait until athom approves. Hopefully today or tomorrow...

**Comment by Lansuper** [comment]
Version 2.0.3 also not working. Error says zone_data.forEach is not a function  at ThermostatDevice._sync (/drivers/thermostat/device.js:112:17)
at ontimeout (timers.js:498:11) etc...
If you have a solution in a new version, please add me (e.lansu at home.nl) to the alfa channel.

**Comment by ralfvd** [comment]
Hi, 

It seems that most issues are solved, but I didn’t ‘solve’ all situations . If you are willing to do some extra testing with me, I will add you to the alpha channel and issue a release with a lot of logging, which will hopefully appear in the crashlog. 

It would be even better if you could run the app locally via CLI, but I understand if that is too much work. 

Thanks for understanding

RAlf
 


On 21 January 2019 at 18:03:52, Lansuper (notifications@github.com) wrote:

Version 2.0.3 also not working. Error says zone_data.forEach is not a function at ThermostatDevice._sync (/drivers/thermostat/device.js:112:17)
at ontimeout (timers.js:498:11) etc...
If you have a solution in a new version, please add me (e.lansu at home.nl) to the alfa channel.

**Comment by Lansuper** [comment]
Not the work is the problem, but that I have no idea what CLI is... Please contact me directly by mail so we can start testing and maybe even explain me how to help you better (I am a moderately experienced PHP programmer)

**Comment by ralfvd** [comment]
This issue was solved somewhere in V2.  As V2 is now in stable, I'll close this issue. Please create a new issue if you encounter any issue
